### ISSUE TITLE
完了，忘了你谁了😱，请告诉我，你是？😭

### ISSUE THREAD

**Issue by DsCodeStudio** [yuan-yy/ALLMessage#1]

**Comment by yuan-yy** [comment]
我，你都忘记了吗，伤心啊



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年5月4日(周二) 晚上11:02
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [yuan-yy/ALLMessage] 完了，忘了你谁了😱，请告诉我，你是？😭 (#1)

**Comment by DsCodeStudio** [comment]
不是啊，在其他平台发个消息我，GitHub 上没办法大备注，你头像好像换了，哭了，认不到喽😭
